### PR TITLE
DropTarget hint and DropHighlightAdorner background brush

### PR DESCRIPTION
**Pull request by mangoyoga80**
## What changed?
* Added some null checking in DefaultDropHandler.
* Minor changes to base class `DropTargetAdorner` with null check and some base properties
 
## Feature DropTargetHighlightBrush
* Added new feature for changing the brush of highlight adorner.
* Feature is enabled through attached property `dd:DragDrop.DropTargetHighlightBrush`. 
* Updated TreeView\Bound sample 
image

## Feature DropHint
* Added new feature for drop hint adorners to illustrate to the user what drop targets are available for a given drag source.
* Added attached property `dd:DragDrop.UseDropTargetHint` to enable the feature
* Added attached property `dd:DragDrop.DropHintDataTemplate` to override datatemplate for displaying hint
* Made `DragDrop.TryGetDropHandler` and `DragDrop.TryGetDropInfoBuilder` internal
* New method `IDropTarget.DropHint` and new properties on `IDropInfo` which may be breaking change
* `dd:DragDrop.UseDropTargetHint` added in SettingsView to enable for all demos using these settings
* The gif demonstrates the functionality
DragHint-Demo
* Updated sample Mixed\DragDropContext to use Hint and Error hints
DragHint-DefaultBehavior

_Closed issues._
#487 Added drop target hints
#488 Added the ability to change the brush of hint adorner.

### CODE REVIEW

**Comment by bsundsbo** [comment]
@punker76 any chance you are able to take a look at this PR in the near future?

Happy Easter

**Comment by bsundsbo** [comment]
> @punker76 any chance you are able to take a look at this PR in the near future?
> 
> Happy Easter

@punker76 Hi. I just wanted to follow up on this PR in case you have more time these days :)

**Comment by punker76** [comment]
@bsundsbo I will take a look in next days

**Comment by punker76** [comment]
Hi @mangoyoga80, I've finally had a look at your changes! I really like the feature. I only have one concern at the moment. Since an adorner is also used here for highlighting, the DropTargetAdorner is now always behind the HighlightAdorner. This cannot be prevented, as in WPF all adorners always get the same zIndex in the AdornerLayer.

2024-09-11_14h13_41

But I already have an idea how we can get this under control. Perhaps I will first adopt your changes and then build my idea on them. But in any case, thanks for your contribution here!!!

/cc @bsundsbo

**Comment by mangoyoga80** [comment]
> Hi @mangoyoga80, I've finally had a look at your changes! I really like the feature. I only have one concern at the moment. Since an adorner is also used here for highlighting, the DropTargetAdorner is now always behind the HighlightAdorner. This cannot be prevented, as in WPF all adorners always get the same zIndex in the AdornerLayer.
> 
> 2024-09-11_14h13_41
> 
> But I already have an idea how we can get this under control. Perhaps I will first adopt your changes and then build my idea on them. But in any case, thanks for your contribution here!!!
> 
> /cc @bsundsbo

I've not seen that issue as I've not used similar scenarios. Great you have some ideas how to fix. 
Glad you like the feature

**Comment by punker76** [comment]
@mangoyoga80 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
