### PR TITLE
Generalized scrollbar/button/textbox drag detection

### PR DESCRIPTION
**Pull request by emsaks**
Instead of checking for ButtonBase etc., just canel drag (in MouseMove) if the mouse is captured by the OriginalSource. (We still need DataGrid etc. because some UI parts don't capture...)
[My VS might have reformatted some code]

### CODE REVIEW

**Comment by emsaks** [comment]
I can't say I've read the source thoroughly, so I don't know what trade-offs there might be. Please let me know.

**Comment by punker76** [comment]
>My VS might have reformatted some code

that's really bad, so i don't see the real changes...

**Comment by emsaks** [comment]
I just commented out the checks in PreviewMouseSown, and added a check for IsMouseCaptured in PreviewMouseMove.

**Comment by punker76** [comment]
@emsaks can you revert the formatting? thx

**Pull request closed without merging**
