### PR TITLE
Find correct current adorner layer (root element)

### PR DESCRIPTION
**Pull request by starguy**
Signed-off-by: Rico-E <reissmann@advitec.de>

### CODE REVIEW

**Comment by punker76** [comment]
@starguy hi, thx for the contribution, but

- please add the `<Compile Include="Utilities\RootElementFinder.cs" />` to `GongSolutions.Wpf.DragDrop (NET4).csproj` too
- can you explain a little bit more what exactly was the cause?

thx

**Comment by starguy** [comment]
@punker76 hi, I just added the RootElementFinder to the NET4 project.
I've created this class, because you were looking for the root element at two different positions. First to create the DragAdorner, and secondly to create the DragEffectAdorner. These two positions diverged, especially the root element for the DragEffectAdorner was not correct for a dialog window. So I refactored it, to use the RootElementFinder which finds the correct elemnt even in a dialog window.

**Comment by punker76** [comment]
@starguy :cool: this makes sense, just onyl short note

in

```
var rootElement = RootElementFinder.FindRoot(m_DragInfo.VisualSource);
//                i don't want the fu... windows forms reference
//                if (rootElement == null) {
//                    var elementHost = m_DragInfo.VisualSource.GetVisualAncestor<ElementHost>();
//                    rootElement = elementHost != null ? elementHost.Child : null;
//                }
if (rootElement == null) {
	rootElement = m_DragInfo.VisualSource.GetVisualAncestor<UserControl>();
}
```

i think we can put this in the new FindRoot method too

```
if (rootElement == null) {
	rootElement = m_DragInfo.VisualSource.GetVisualAncestor<UserControl>();
}
```

**Comment by starguy** [comment]
@punker76 Yes, indeed. I think that would be usefull for forms, when the content of the host is an UserControl.

**Pull request merged**
