### PR TITLE
fix touch support 

### LINKED ISSUE #418: Drag&Drop on a touch device
Trying to drag an item on a touch screen causes the mouse pointer to freeze for seconds and follow up the fingeer at random intervals. Please see the attached video sequence where the blue rectangle shows the current behaviour while the red rectangle shows the desired way.
The same operations show no problems if only the mouse pointer is used.

https://user-images.githubusercontent.com/7251838/142870991-389bcbff-ddc1-45e4-82c0-c4ef780a5196.mp4

The problem seems to be caused by the SetWindowsHookEx in MouseHelper.cs

Attached is a fix for the problem based on the current sources. The fix uses a System.Windows.Threading.DispatcherTimer instead of the hook and can be activated by setting a new "MouseMoveTimerTriggered" attached property.

Please have a  look a the modifications. It would be great if you could add them to you project.

I really apprechiate your work!!

[DraDropTouch.zip](https://github.com/punker76/gong-wpf-dragdrop/files/7581788/DraDropTouch.zip)

### PR DESCRIPTION
**Pull request by dmg-hamann**
## What changed?

Added the code @KKauK suggested in #418 and enhanced Showcase to test touch. I was able to test on a touch panel and after the adjustments it works fine.

Closes #418

### CODE REVIEW

**Comment by jizc** [comment]
I'm sure this was unintentional, but your PR undoes the changes from #426 and #430. You may want to rebase.

**Comment by dmg-hamann** [comment]
Oh Im sorry. I'll fix that.

**Comment by dmg-hamann** [comment]
I made the mistake to use the files mentioned in the issue which were based on an older commit and I replaced the whole content. I merged the code

**Comment by las-nsc** [comment]
@dmg-hamann @punker76, any chance of getting this in? It's making our solution unusable.

**Comment by punker76** [comment]
@las-nsc I am still on holiday. Next week I can have a look at this.

**Comment by John-Welch** [comment]
(@las-nsc's colleague here)
@punker76  Do you have a rough idea when this might be merged and pushed into NuGet? We'd much prefer to pick up an updated package from there than have to fork the repo and apply the PR locally to get the fix for our solution.

**Comment by punker76** [comment]
@dmg-hamann your changes have been merged, thanks for your contribution 👍

**Comment by John-Welch** [comment]
Thanks very much for the fix - I've upgraded to 3.2.0 using NuGet and the propblem has gone away.

**Pull request merged**
