### PR TITLE
Empty treeviewitem and common moving support

### LINKED ISSUE #31: Dragging an element as a child to an empty treeview item does not work
_Original author: gmcnic...@gmail.com (February 18, 2011 19:21:53)_

Dropping a child element into a treeviewitem will not add the element as a child of the treeviewitem.

Take the default sample application, look at the 'bound treeview' window and drag all of the children from one parent to another, then once empty, try to drag one of the children back to the original parent.

_Original issue: http://code.google.com/p/gong-wpf-dragdrop/issues/detail?id=31_

### PR DESCRIPTION
**Pull request by punker76**
yes... now it's time to support empty `TreeViewItem`'s ...

- [x] it's now possible to drop data on empty treeview items
- [x] re-create the `EffectAdorner` if drag&drop `Effects` are changed
- [x] the drop target adorner is now expanded to the right
- [x] it's now also possible to move any data to another `ItemsControl` with the `ALT` key (common explorer action)
- [x] change default behavior (move or copy, now default is copy)

drag drop_on_empty_treeview_item

grab the latest alpha: https://www.nuget.org/packages/gong-wpf-dragdrop/

Closes #31

### CODE REVIEW

**Comment by punker76** [comment]
@christianhuening @dudiam @chandramouleswaran @AnnekeHeelsum @AnnekeHeelsum @Toprakete testable with `gong-wpf-dragdrop 1.0.0-ALPHA002`

**Comment by punker76** [comment]
next change would be (yes a breaking change)

- change default behavior to `Move` for drag&drop to another control
- use `SHIFT` drag&drop for copy drag&drop

/cc @thoemmi what do you think?

/cc @christianhuening @dudiam @chandramouleswaran @AnnekeHeelsum @AnnekeHeelsum @Toprakete

**Comment by christianhuening** [comment]
@punker76  Thanks for updating this solution! The project I used it for has long gone into production and is no longer maintained by me. But I nonetheless appreciate the new stuff and the fixes for future projects! Great! 
The behavior regarding moving and copying sounds reasonable! Should be configurable though.

Cheers,
Christian

**Comment by enkafan** [comment]
ran into a bug testing this out. easy to reproduce using the Issue 65 view. Dragging an item with children to a top level position will cause it to lose the children of that item.

**Comment by punker76** [comment]
@enkafan ups, i should fix this 8-D

**Comment by punker76** [comment]
@enkafan it's now fixed in 1.0.0-ALPHA003

but you should noticed, issue #65 example is a very special example...

```xaml
<TreeView Grid.Column="0"
          Grid.Row="1"
          dd:DragDrop.IsDropTarget="True"
          dd:DragDrop.IsDragSource="True"
          dd:DragDrop.UseDefaultDragAdorner="True">
  <TreeViewItem Header="A TreeViewItem with ItemsSource"
                ItemsSource="{Binding TreeCollection}">
    <TreeViewItem.ItemTemplate>
      <HierarchicalDataTemplate ItemsSource="{Binding Children}">
        <TextBlock Text="{Binding Caption}" />
      </HierarchicalDataTemplate>
    </TreeViewItem.ItemTemplate>
  </TreeViewItem>
  <TreeView.ItemTemplate>
    <HierarchicalDataTemplate ItemsSource="{Binding Children}">
      <TextBlock Text="{Binding Caption}" />
    </HierarchicalDataTemplate>
  </TreeView.ItemTemplate>
</TreeView>
```

**Comment by Toprakete** [comment]
Hi,
thx for updating. Works very fine for my need.
Still one thing: Start Sample, Select Bound TreeView and click below the tree-items.
It crashes in ItemsControlExtensions.cs because the SelectedItemProperty is read only.

Thx and best regards
Toprakete

**Pull request merged**
